apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: bettaibiwalid/gestion-station-ski:1.0.0
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-db:3306/walid-db
            - name: SPRING_DATASOURCE_USERNAME
              value: walid
            - name: SPRING_DATASOURCE_PASSWORD
              value: walid
